// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AuthLoginResponse, ActuatorsGetActuatorsResponse, ActuatorsGetActuatorByIdData, ActuatorsGetActuatorByIdResponse, ActuatorsMoveData, ActuatorsMoveResponse, ActuatorsStopData, ActuatorsStopResponse } from './types.gen';

/**
 * Login as admin
 * @returns unknown Successful response
 * @throws ApiError
 */
export const authLogin = (): CancelablePromise<AuthLoginResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/auth/login',
    errors: {
        default: 'Error response'
    }
}); };

/**
 * Read all actuators
 * @returns unknown Successful response
 * @throws ApiError
 */
export const actuatorsGetActuators = (): CancelablePromise<ActuatorsGetActuatorsResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/actuators',
    errors: {
        default: 'Error response'
    }
}); };

/**
 * Read an actuator by id
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Successful response
 * @throws ApiError
 */
export const actuatorsGetActuatorById = (data: ActuatorsGetActuatorByIdData): CancelablePromise<ActuatorsGetActuatorByIdResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/actuators/{id}',
    path: {
        id: data.id
    },
    errors: {
        default: 'Error response'
    }
}); };

/**
 * Moves an actuator by id
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Successful response
 * @throws ApiError
 */
export const actuatorsMove = (data: ActuatorsMoveData): CancelablePromise<ActuatorsMoveResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/actuators/{id}/move',
    path: {
        id: data.id
    },
    errors: {
        default: 'Error response'
    }
}); };

/**
 * Stops an actuator by id
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Successful response
 * @throws ApiError
 */
export const actuatorsStop = (data: ActuatorsStopData): CancelablePromise<ActuatorsStopResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/actuators/{id}/stop',
    path: {
        id: data.id
    },
    errors: {
        default: 'Error response'
    }
}); };