// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type { AuthLoginError, AuthLoginResponse, ActuatorsGetActuatorsError, ActuatorsGetActuatorsResponse, ActuatorsGetActuatorByIdData, ActuatorsGetActuatorByIdError, ActuatorsGetActuatorByIdResponse, ActuatorsMoveData, ActuatorsMoveError, ActuatorsMoveResponse, ActuatorsStopData, ActuatorsStopError, ActuatorsStopResponse } from './types.gen';

/**
 * Login as admin
 */
export const authLogin = (options?: Options) => { return (options?.client ?? client).post<AuthLoginResponse, AuthLoginError>({
    ...options,
    url: '/auth/login'
}); };

/**
 * Read all actuators
 */
export const actuatorsGetActuators = (options?: Options) => { return (options?.client ?? client).get<ActuatorsGetActuatorsResponse, ActuatorsGetActuatorsError>({
    ...options,
    url: '/actuators'
}); };

/**
 * Read an actuator by id
 */
export const actuatorsGetActuatorById = (options: Options<ActuatorsGetActuatorByIdData>) => { return (options?.client ?? client).get<ActuatorsGetActuatorByIdResponse, ActuatorsGetActuatorByIdError>({
    ...options,
    url: '/actuators/{id}'
}); };

/**
 * Moves an actuator by id
 */
export const actuatorsMove = (options: Options<ActuatorsMoveData>) => { return (options?.client ?? client).post<ActuatorsMoveResponse, ActuatorsMoveError>({
    ...options,
    url: '/actuators/{id}/move'
}); };

/**
 * Stops an actuator by id
 */
export const actuatorsStop = (options: Options<ActuatorsStopData>) => { return (options?.client ?? client).post<ActuatorsStopResponse, ActuatorsStopError>({
    ...options,
    url: '/actuators/{id}/stop'
}); };